appearanceSelection = { # Use this for finding a style for someone for an outfit
    "style_category": {
        "streetwear",
        "old_money",
        "casual",
        "sporty",
        "minimalist",
        "luxury",
        "vintage",
        "preppy",
        "grunge",
        "clean_fit",
        "business_casual",
        "summer_fit",
        "winter_fit",
        "formal",
        "partywear",
        "athleisure",
        "y2k",
        "boho",
        "edgy",
        "smart_casual"
    },

    "color_palette": {
        "dark_neutrals",  # black gray charcoal
        "light_neutrals", # white beige cream
        "earth_tones",    # brown olive tan
        "monochrome_black",
        "monochrome_white",
        "blue_tones",
        "red_tones",
        "green_tones",
        "pastels",
        "bright_colors",
        "muted_colors",
        "warm_colors",
        "cool_colors",
        "denim_heavy",
        "black_and_white",
        "golden_tones",
        "beach_tones",
        "luxury_neutrals"
    },

    "accessories": {
        "none",
        "silver_chain",
        "gold_chain",
        "watch",
        "bracelets",
        "rings",
        "earrings",
        "sunglasses",
        "hat",
        "beanie",
        "hood_up",
        "crossbody_bag",
        "designer_bag",
        "belt",
        "scarf",
        "necklace_layered",
        "pearls",
        "cap",
        "headphones",
        "glasses"
    },

    "presentation": {
        "clean",
        "polished",
        "confident",
        "relaxed",
        "laid_back",
        "mysterious",
        "bold",
        "luxurious",
        "soft",
        "playful",
        "serious",
        "athletic",
        "trendy",
        "classy",
        "chill",
        "high_energy",
        "romantic",
        "creative",
        "edgy",
        "effortless"
    }
}
musicSelection = {
    "Genre": {
        "rap",
        "rnb",
        "pop",
        "indie",
        "afrobeats",
        "country",
        "rock",
        "alternative",
        "latin",
        "house",
        "edm",
        "trap",
        "drill",
        "jazz",
        "lofi",
        "reggaeton",
        "kpop",
        "soul",
        "funk",
        "phonk"
    },

    "Energy" : {
        "chill",
        "calm",
        "smooth",
        "laid_back",
        "hype",
        "aggressive",
        "party",
        "upbeat",
        "romantic",
        "sad",
        "emotional",
        "dreamy",
        "confident",
        "dark",
        "moody",
        "late_night",
        "summer",
        "gym",
        "focused",
        "nostalgic"
    },

    "Era" : {
        "70s",
        "80s",
        "90s",
        "2000s",
        "2010s",
        "2020s",
        "classic",
        "modern",
        "timeless",
        "throwback",
        "currently_trending",
        "golden_age"
    },

    "Artist": "", # user input string
}
vibeSelection = {
    "happy",
    "sad",
    "chill",
    "hype",
    "confident",
    "romantic",
    "fun",
    "serious",
    "mysterious",
    "relaxed",
    "energetic",
    "calm",
    "bold",
    "soft",
    "classy",
    "cool",
    "playful",
    "dreamy",
    "carefree",
    "motivated"
}
